/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'bruce.huang' at '2016/6/17 上午 11:55' with Gradle 2.13
 *
 * @author bruce.huang, @date 2016/6/17 上午 11:55
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
