package spring;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'weich' at '2016/5/11 下午 9:05' with Gradle 2.12
 *
 * @author weich, @date 2016/5/11 下午 9:05
 */
public class SomeLibrary {
    public boolean someLibraryMethod() {
        return true;
    }
    public static void main(String [] args){
    	System.out.println(123);
    }
}
